version: '3'

services:
  h5ai:
    image: bixidock/h5ai
    volumes:
      - ./data:/var/www:rw
    restart: always
  aria2:
    image: wahyd4/aria2-ui:h5ai
    ports:
      - "8000:80"
      - "443:443"
      - "6800:6800"
    volumes:
      - ./data:/var/www:rw
    # volumes:
    #   - /some_folder:/root/conf/key
    #   - ~/test/aria2.conf:/root/conf/aria2.conf
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    links:
      - h5ai:file-manager
    restart: always
