version: '2'

services:
  nextcloud:
    image: nextcloud
    volumes:
      - /data/nextcloud:/var/www/html
      - /data:/user-files
    restart: always
  aria2:
    image: wahyd4/aria2-ui:nextcloud
    ports:
      - "8000:80"
      - "6800:6800"
      - "443:443"
    volumes_from:
      - nextcloud
    # volumes:
    #   - /some_folder:/root/conf/key
    #   - ~/test/aria2.conf:/root/conf/aria2.conf
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager
    restart: always


