version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    # volumes:
    #   - /data/db:/var/lib/mysql #mysql database
  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    volumes:
      - /data:/user-files
  aria2:
    image: wahyd4/aria2-ariang:caddy-filerun
    links:
      - web:file-manager
    ports:
      - "8000:80"
      - "6800:6800"
      - "443:443"
    environment:
      - DOMAIN=localhost:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    # volumes:
    #   - /some_folder:/root/conf/key
    volumes_from:
      - web

